
default: all

all:
	@make -C deveasy/dev_easy1
	@make -C deveasy/dev_easy2
	@make -C deveasy/dev_easy3
	@make -C deveasy/dev_easy_irt1
	@make -C deveasy/dev_easy_im
	@make -C deveasy/dev_easy_cert
	@make -C easy/pnioeasy1
	@make -C easy/pnioeasy2
	@make -C easy/pnioeasy3
	@make -C easy/pnioeasy4
	@make -C easy/pnioeasy_irt1

clean:
	@make -C deveasy/dev_easy1 clean
	@make -C deveasy/dev_easy2 clean
	@make -C deveasy/dev_easy3 clean
	@make -C deveasy/dev_easy_irt1 clean
	@make -C deveasy/dev_easy_im clean
	@make -C deveasy/dev_easy_cert clean
	@make -C easy/pnioeasy1 clean
	@make -C easy/pnioeasy2 clean
	@make -C easy/pnioeasy3 clean
	@make -C easy/pnioeasy4 clean
	@make -C easy/pnioeasy_irt1 clean
